uploads = []
outputs = []

[[generated]]
id = "IvZ09IoiHmFyjQIwdMZHb"
uri = "file://artifacts/lets-play/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gf-W1l9CorXMzRbF3fckE"
uri = "file://artifacts/lets-play/assets/images/basketball_hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "P0381Fk34jaZhbHEaRB_Q"
uri = "file://artifacts/lets-play/assets/images/tennis_hero.png"
type = "image"
title = "generated_image"
