import { User, Game, Conversation } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "user_jordan",
    name: "Jordan Martinez",
    username: "jordan_plays",
    email: "jordan@example.com",
    password: "password123",
    role: "coach",
    sports: ["basketball", "pickleball"],
    location: "Harlem, NYC",
    bio: "Former college basketball player. Now coaching the next generation and hosting weekly pickup games in Harlem.",
    verificationStatus: "verified",
    followingIds: [],
    rating: 4.8,
    gamesPlayed: 142,
    onboardingComplete: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "user_sarah",
    name: "Sarah Chen",
    username: "sarah_ace",
    email: "sarah@example.com",
    password: "password123",
    role: "pro",
    sports: ["tennis", "golf"],
    location: "Upper West Side, NYC",
    bio: "ATP-ranked tennis professional. Offering private lessons and group clinics in Central Park.",
    verificationStatus: "verified",
    followingIds: [],
    rating: 4.9,
    gamesPlayed: 289,
    onboardingComplete: true,
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "user_mike",
    name: "Mike Thompson",
    username: "mike_bball",
    email: "mike@example.com",
    password: "password123",
    role: "player",
    sports: ["basketball", "chess"],
    location: "Brooklyn, NYC",
    bio: "Weekend warrior. Love pickup basketball and strategy games. Always down for a game.",
    verificationStatus: "none",
    followingIds: ["user_jordan"],
    rating: 4.2,
    gamesPlayed: 58,
    onboardingComplete: true,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "user_aisha",
    name: "Aisha Johnson",
    username: "aisha_serves",
    email: "aisha@example.com",
    password: "password123",
    role: "player",
    sports: ["tennis", "poker"],
    location: "Harlem, NYC",
    bio: "Tennis enthusiast and poker hobbyist. Looking for competitive and casual games around Manhattan.",
    verificationStatus: "none",
    followingIds: ["user_sarah"],
    rating: 4.5,
    gamesPlayed: 34,
    onboardingComplete: true,
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "user_carlos",
    name: "Carlos Rivera",
    username: "carlos_pickle",
    email: "carlos@example.com",
    password: "password123",
    role: "coach",
    sports: ["pickleball", "tennis"],
    location: "Queens, NYC",
    bio: "Pickleball addict and certified coach. Hosting beginner-friendly sessions every weekend.",
    verificationStatus: "verified",
    followingIds: [],
    rating: 4.7,
    gamesPlayed: 91,
    onboardingComplete: true,
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
  },
  {
    id: "user_emma",
    name: "Emma Park",
    username: "emma_chess",
    email: "emma@example.com",
    password: "password123",
    role: "player",
    sports: ["chess", "pokemon"],
    location: "Lower East Side, NYC",
    bio: "Chess club organizer and Pokémon TCG collector. Looking for competitive players and friendly matches.",
    verificationStatus: "none",
    followingIds: [],
    rating: 4.3,
    gamesPlayed: 76,
    onboardingComplete: true,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
  },
];

const futureDate = (daysAhead: number, hour: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

export const MOCK_GAMES: Game[] = [
  {
    id: "game_1",
    createdBy: "user_jordan",
    organizerId: "user_jordan",
    sport: "basketball",
    title: "Friday Night Hoops",
    description: "Pickup basketball at the Chelsea courts. All skill levels welcome. Bring water and good vibes.",
    date: futureDate(2, 19),
    startTime: "7:00 PM",
    endTime: "9:00 PM",
    locationName: "Chelsea Recreation Center",
    city: "Chelsea, Manhattan",
    ageGroup: "all",
    participationGroup: "all",
    skillLevel: "all",
    maxPlayers: 10,
    participants: ["user_jordan", "user_mike"],
    type: "game",
    isPaid: false,
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80",
    messages: [
      {
        id: "msg_1_1",
        senderId: "user_jordan",
        body: "Looking forward to this one! Courts just got resurfaced.",
        createdAt: new Date(Date.now() - 3600000).toISOString(),
        isHidden: false,
      },
      {
        id: "msg_1_2",
        senderId: "user_mike",
        body: "I'll bring extra balls. See everyone there!",
        createdAt: new Date(Date.now() - 1800000).toISOString(),
        isHidden: false,
      },
    ],
  },
  {
    id: "game_2",
    createdBy: "user_sarah",
    organizerId: "user_sarah",
    sport: "tennis",
    title: "Beginner Tennis Clinic",
    description: "Structured lesson for beginners and intermediate players. Learn proper technique, footwork, and court positioning. Rackets available if needed.",
    date: futureDate(3, 10),
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    locationName: "Central Park Tennis Center",
    city: "Upper West Side, Manhattan",
    ageGroup: "all",
    participationGroup: "all",
    skillLevel: "beginner",
    maxPlayers: 6,
    participants: ["user_sarah", "user_aisha"],
    type: "lesson",
    isPaid: true,
    price: 45,
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800&q=80",
    messages: [
      {
        id: "msg_2_1",
        senderId: "user_sarah",
        body: "Please arrive 10 minutes early for warm-up stretches.",
        createdAt: new Date(Date.now() - 7200000).toISOString(),
        isHidden: false,
      },
    ],
  },
  {
    id: "game_3",
    createdBy: "user_carlos",
    organizerId: "user_carlos",
    sport: "pickleball",
    title: "Weekend Pickleball Mixer",
    description: "Mixed doubles pickleball for all levels. Come meet other players and enjoy some fast-paced rallies on Roosevelt Island.",
    date: futureDate(4, 14),
    startTime: "2:00 PM",
    endTime: "5:00 PM",
    locationName: "Roosevelt Island Courts",
    city: "Roosevelt Island, NYC",
    ageGroup: "adult",
    participationGroup: "all",
    skillLevel: "intermediate",
    maxPlayers: 8,
    participants: ["user_carlos"],
    type: "game",
    isPaid: false,
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&q=80",
    messages: [],
  },
  {
    id: "game_4",
    createdBy: "user_emma",
    organizerId: "user_emma",
    sport: "chess",
    title: "Rapid Chess Night",
    description: "Blitz and rapid chess rounds at the coffee shop. Bring your own clock or use ours. All ratings welcome — we'll match you with someone at your level.",
    date: futureDate(2, 18),
    startTime: "6:00 PM",
    endTime: "10:00 PM",
    locationName: "The Chess Cafe",
    city: "Brooklyn, NYC",
    ageGroup: "all",
    participationGroup: "all",
    skillLevel: "all",
    maxPlayers: 16,
    participants: ["user_emma", "user_mike"],
    type: "game",
    isPaid: false,
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&q=80",
    messages: [],
  },
  {
    id: "game_5",
    createdBy: "user_jordan",
    organizerId: "user_jordan",
    sport: "basketball",
    title: "Play with a Pro: 3-on-3",
    description: "Get coached and compete alongside Jordan Martinez — former D1 player. Focus on offensive plays and team communication. Limited to 6 spots for maximum personal attention.",
    date: futureDate(5, 16),
    startTime: "4:00 PM",
    endTime: "6:00 PM",
    locationName: "Rucker Park",
    city: "Harlem, Manhattan",
    ageGroup: "young_adult",
    participationGroup: "all",
    skillLevel: "intermediate",
    maxPlayers: 6,
    participants: ["user_jordan"],
    type: "pro_game",
    isPaid: true,
    price: 30,
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=800&q=80",
    messages: [],
  },
  {
    id: "game_6",
    createdBy: "user_aisha",
    organizerId: "user_aisha",
    sport: "poker",
    title: "Friendly Poker Night",
    description: "Texas Hold'em, low stakes, good company. BYOB snacks. Max buy-in $50.",
    date: futureDate(3, 20),
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    locationName: "Private Venue",
    city: "Harlem, Manhattan",
    ageGroup: "adult",
    participationGroup: "all",
    skillLevel: "beginner",
    maxPlayers: 8,
    participants: ["user_aisha"],
    type: "game",
    isPaid: false,
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1541278107931-e006523892df?w=800&q=80",
    messages: [],
  },
  {
    id: "game_7",
    createdBy: "user_emma",
    organizerId: "user_emma",
    sport: "pokemon",
    title: "Pokémon TCG Tournament",
    description: "Standard format Pokémon card tournament. Bring your own deck. Top 3 players win prizes. Check the LES Community Center rules before coming.",
    date: futureDate(4, 13),
    startTime: "1:00 PM",
    endTime: "6:00 PM",
    locationName: "LES Community Center",
    city: "Lower East Side, Manhattan",
    ageGroup: "all",
    participationGroup: "all",
    skillLevel: "intermediate",
    maxPlayers: 12,
    participants: ["user_emma"],
    type: "game",
    isPaid: false,
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1613771404721-1f92d799e49f?w=800&q=80",
    messages: [],
  },
  {
    id: "game_8",
    createdBy: "user_sarah",
    organizerId: "user_sarah",
    sport: "golf",
    title: "Early Morning Golf Round",
    description: "18 holes at Forest Park Golf Course. Tee time locked. Join if you want to make it a foursome. Relaxed pace, all handicaps welcome.",
    date: futureDate(4, 8),
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    locationName: "Forest Park Golf Course",
    city: "Queens, NYC",
    ageGroup: "adult",
    participationGroup: "all",
    skillLevel: "intermediate",
    maxPlayers: 4,
    participants: ["user_sarah", "user_carlos"],
    type: "game",
    isPaid: false,
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=80",
    messages: [],
  },
  {
  id: "game_9",
  createdBy: "user_ali",
  organizerId: "user_ali",
  sport: "cricket",
  title: "Weekend Cricket Match",
  description: "Friendly 20-over cricket match at Central Sports Ground. Looking for players to complete both teams. All skill levels are welcome. Bring your own gear if possible.",
  date: futureDate(5, 7),
  startTime: "7:00 AM",
  endTime: "11:00 AM",
  locationName: "Central Sports Ground",
  city: "Karachi, Pakistan",
  ageGroup: "adult",
  participationGroup: "all",
  skillLevel: "intermediate",
  maxPlayers: 22,
  participants: ["user_ali", "user_ahmed", "user_hassan"],
  type: "game",
  isPaid: false,
  status: "active",
  imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80",
  messages: [],
}
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv_1",
    type: "direct",
    participantIds: ["CURRENT_USER", "user_jordan"],
    messages: [
      {
        id: "dm_1_1",
        senderId: "user_jordan",
        content: "Hey! Saw you're interested in Friday hoops. Courts are great right now.",
        createdAt: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: "dm_1_2",
        senderId: "CURRENT_USER",
        content: "Definitely joining! Is there a specific spot to meet?",
        createdAt: new Date(Date.now() - 82800000).toISOString(),
      },
      {
        id: "dm_1_3",
        senderId: "user_jordan",
        content: "Meet at the main entrance on 25th St. Can't miss it.",
        createdAt: new Date(Date.now() - 79200000).toISOString(),
      },
    ],
    lastMessageAt: new Date(Date.now() - 79200000).toISOString(),
  },
  {
    id: "conv_2",
    type: "direct",
    participantIds: ["CURRENT_USER", "user_sarah"],
    messages: [
      {
        id: "dm_2_1",
        senderId: "user_sarah",
        content: "Spots still open for the tennis clinic — let me know if you have questions!",
        createdAt: new Date(Date.now() - 43200000).toISOString(),
      },
    ],
    lastMessageAt: new Date(Date.now() - 43200000).toISOString(),
  },
];
